import Head from 'next/head';
import { useIntl } from 'react-intl';
import styles from '../styles/Home.module.css';

export default function Home() {
  const { formatMessage } = useIntl();
  const f = (id) => formatMessage({ id });
  return (
    <div className={styles.container}>
      <Head>
        <title>{f('navBarNew')}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          If you would like to get involved with the church.
        </h1>
      </main>
    </div>
  );
}
